server:
  log_level: info
metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
integrations:
  node_exporter:
    enabled: true
    instance: ${PROMETHEUS_INSTANCE_LABEL}  
  prometheus_remote_write:
    - url: ${PROMETHEUS_URL}
      basic_auth:
        username: ${PROMETHEUS_USERNAME}
        password: ${PROMETHEUS_PASSWORD}
