# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

#require: rubocop-rails

Layout/LineLength:
  Enabled: false
  Exclude:
    - 'db/schema.rb'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/AndOr:
  Enabled: false

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLines:
  Description: "Don't use several empty lines in a row."
  StyleGuide: '#two-or-more-empty-lines'
  Enabled: false

