services:
  app:
    restart: "no"
    stdin_open: true
    tty: true
  sidekiq:
    restart: "no"
  mqtt-task-main-1:
    restart: "no"
  mqtt-task-main-2:
    restart: "no"
  mqtt-task-secondary:
    restart: "no"
  telnet-task:
    restart: "no"
  grafana:
    entrypoint: ["echo", "Grafana service disabled in development"]
    restart: "no"
