services:
  app: &app
    build:
      context: ../.
      # Skip installing development & test gems in production, saves 20s build time.
      # If developing with Docker, this line might need to be commented out.
      args:
        - BUNDLE_WITHOUT=test development
    env_file: ../.env
    ports:
      - "3000:3000"
    depends_on:
      # We disable some containers in production
      - db
      - auth
      - redis
      - sidekiq
      - mqtt-task
      - telnet-task
      - push
      - app-migrations
      #- mqtt
    restart: always
    deploy:
      resources:
        limits:
          memory: 2gb
    volumes:
      - "../:/app"
    #command: rails server -p 3000 -b '0.0.0.0'
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      # For this to take effect, remove init/timeout, and in Gemfile, fix "rack-timeout" to not require anything.
      RACK_TIMEOUT_SERVICE_TIMEOUT: 25
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  app-migrations:
    <<: *app
    depends_on:
      - db
    ports: []
    entrypoint: ["bash", "-c", "rake db:migrate"]
    restart: no
