services:
  # Check if cassandra cluster is working:
  # docker compose exec cassandra-1 nodetool status
  cassandra-1:
      image: cassandra:3.11.4
      ports:
        # no need to expose all ports?
        - "7000:7000" # Internode, cluster communication
        - "7001:7001" # TLS Internode
        - "7199:7199" # JMX
        - "9042:9042" # CQL native transport
        - "9160:9160" # Thrift client API
      #volumes:
        #- ../sck-cassandra:/var/lib/cassandra

#  cassandra-2:
#    image: cassandra:3.11.4
#    ports:
#      - 9142:9042
#    environment:
#      - CASSANDRA_SEEDS=cassandra-1 # Use IP if on different servers
#    depends_on:
#      - cassandra-1
#    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
#
#  cassandra-3:
#    image: cassandra:3.11.4
#    ports:
#      - 9242:9042
#    environment:
#      - CASSANDRA_SEEDS=cassandra-1 # Use IP if on different servers
#    depends_on:
#      - cassandra-1
#    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'
