services:
   db:
    image: postgres:10
    command: -c max_connections=200
    volumes:
      - sck-postgres:/var/lib/postgresql/data
    env_file: ../.env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
   #environment:
      # NOTE: Postgres 9.5 stopped allowing connections without passwords.
      # Enable this if needed.
     #- POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  sck-postgres:
