services:
   db:
    image: postgres:10
    volumes:
      - sck-postgres:/var/lib/postgresql/data
   #environment:
      # NOTE: Postgres 9.5 stopped allowing connections without passwords.
      # Enable this if needed.
     #- POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  sck-postgres: