services:
  sidekiq:
    build: ../.
    env_file: ../.env
    command: bundle exec sidekiq -c 100
    restart: always
    volumes:
      - "../log:/app/log"
    environment:
      db_pool_size: 100
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 4G
