services:
  sidekiq:
    build: ../.
    env_file: ../.env
    command: bundle exec sidekiq
    restart: always
    volumes:
      - "../log:/app/log"
    environment:
      db_pool_size: 30
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
