services:
  web:
    image: nginx
    depends_on:
      app:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl http://app:3000"]
      timeout: 10s
    restart: always
    ports:
      - 80:80
      - 80:80/udp
      - 443:443
      - 443:443/udp
    volumes:
      - ../public:/app/public
      - ../scripts/nginx-conf/api.smartcitizen.me.conf:/etc/nginx/conf.d/api.smartcitizen.me.conf
      - ../scripts/nginx.conf:/etc/nginx/nginx.conf
      - ../scripts/certs:/etc/ssl:ro
