name: Ruby

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env file
        uses: canastro/copy-file-action@master
        with:
          source: "env.example"
          target: ".env"

      - name: Build the Stack
        run: "docker compose build"

      - name: Start dependencies
        run: "docker compose up -d --no-deps db redis app"

      - name: Run all tests
        run: "docker compose exec app ./ci.sh"

      - name: Teardown the stack
        run: "docker compose down"

