name: Ruby

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env file
        uses: canastro/copy-file-action@master
        with:
          source: "env.example"
          target: ".env"

      - name: Build the Stack
        run: "docker compose build"

      - name: Run all tests
        run: "docker compose run app -- ./ci.sh"

      - name: Tear down the Stack
        run: "docker compose down"
