name: Ruby

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env file
        uses: canastro/copy-file-action@master
        with:
          source: "env.example"
          target: ".env"
      - uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: "./compose.yml"
          entrypoint: "./entrypoint.sh"
          workdir: "./"
          service: app
          command: "./ci.sh"
          docker-compose-version: "2.27.0"
